name: feeling-finder
grade: stable
adopt-info: feeling-finder
summary: A fast and beautiful emoji picker.
description: |
  Fast and beautiful emoji picker. Easily find the perfect emoji by genre.
base: core22
confinement: strict
compression: lzo
architectures:
  - build-on: amd64
  
apps:
  feeling-finder:
    command: feeling_finder 
    extensions: [gnome]
    plugs:
      - home
      - network
      - optical-drive
      - removable-media
    common-id: codes.merritt.FeelingFinder
  
parts:
  feeling-finder:
    plugin: flutter
    source: https://github.com/Merrit/feeling_finder.git
    source-tag: v1.0.0
    build-packages:
      - curl
      - libsecret-1-dev
      - libjsoncpp-dev
    stage-packages:
      - libsecret-1-0
      - libjsoncpp25    
    override-pull: |
      craftctl default
      craftctl set version=$(git describe --tags --abbrev=0 | cut -c 2-)
           

